name = "Cyclotomics"
uuid = "da8f5974-afbb-4dc8-91d8-516d5257c83b"
authors = ["kalmarek <kalmar@amu.edu.pl>"]
version = "0.1.0"

[deps]
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Primes = "0.4, 0.5"
julia = "1.3, 1.4"
